---
project: deblur_gan
experiment_desc: fpn_full2

train:
#  files_a: &FILES_A /datasets/my_dataset/**/*.jpg
  #可以使用绝对路径
  files_a: &FILES_A GOPRO_Large/train
  files_b: *FILES_A
#  files_a: &FILES_A ./dataset1/blur/*.png
#  files_b: &FILES_B ./dataset1/sharp/*.png
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: &FILES_B GOPRO_Large/test
  files_b: *FILES_B
#  files_a: &FILES_A
#  files_b: &FILES_B
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  corrupt: null

phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: wgan-gp
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 100
#train_batches_per_epoch: 500
val_batches_per_epoch: 10
batch_size: 320
# image_size: [256, 256]   Not work

optimizer:
  name: adamw
  lr: 0.0001874
scheduler:
  name: cosine
  start_epoch: 10
  min_lr: 0.000000001
